// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lesson-typography/Current.tsx": () => import("../components/mockups/lesson-typography/Current.tsx"),
  "./components/mockups/lesson-typography/DuskReading.tsx": () => import("../components/mockups/lesson-typography/DuskReading.tsx"),
  "./components/mockups/lesson-typography/HumanistClarity.tsx": () => import("../components/mockups/lesson-typography/HumanistClarity.tsx"),
  "./components/mockups/lesson-typography/PaperInk.tsx": () => import("../components/mockups/lesson-typography/PaperInk.tsx")
};
