/**
 * Generates artifacts/tensor-dojo/public/sitemap.xml from the lesson
 * content directory (one <url> per lesson + the four static routes),
 * and keeps every other hardcoded origin in the repo in sync with the
 * same SITE_URL:
 *
 *   - public/robots.txt  → Sitemap: line
 *   - index.html         → og:image / twitter:image absolute URLs
 *
 * Sitemaps and most unfurlers require absolute URLs, so set the
 * deployed origin:
 *
 *   SITE_URL=https://your-domain.example node scripts/generate-sitemap.mjs
 *
 * Re-run whenever lessons are added/removed or the origin changes, or
 * wire it into the deploy step.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const lessonsDir = path.join(root, 'artifacts/tensor-dojo/src/content/lessons');
const out = path.join(root, 'artifacts/tensor-dojo/public/sitemap.xml');
const robotsPath = path.join(root, 'artifacts/tensor-dojo/public/robots.txt');
const indexHtmlPath = path.join(root, 'artifacts/tensor-dojo/index.html');

const siteUrl = (process.env.SITE_URL ?? 'https://tensordojo.vercel.app').replace(/\/$/, '');

const slugs = readdirSync(lessonsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .filter((name) => {
    // Only include folders that actually carry a meta.ts with a slug.
    try {
      const meta = readFileSync(path.join(lessonsDir, name, 'meta.ts'), 'utf8');
      return /slug:\s*['"]/.test(meta);
    } catch {
      return false;
    }
  })
  .sort();

const staticRoutes = ['', 'lessons', 'map'];
const today = new Date().toISOString().slice(0, 10);

const urls = [
  ...staticRoutes.map(
    (r) =>
      `  <url>\n    <loc>${siteUrl}/${r}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>${r === '' ? '1.0' : '0.8'}</priority>\n  </url>`,
  ),
  ...slugs.map(
    (s) =>
      `  <url>\n    <loc>${siteUrl}/lessons/${s}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n    <priority>0.6</priority>\n  </url>`,
  ),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — set SITE_URL to your deployed origin and re-run. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join('\n')}
</urlset>
`;

writeFileSync(out, xml);
console.log(`wrote ${out} (${staticRoutes.length} static + ${slugs.length} lessons)`);

// Keep robots.txt's Sitemap line on the same origin.
const robots = readFileSync(robotsPath, 'utf8');
const nextRobots = robots.replace(
  /^Sitemap: .*$/m,
  `Sitemap: ${siteUrl}/sitemap.xml`,
);
if (nextRobots !== robots) {
  writeFileSync(robotsPath, nextRobots);
  console.log(`updated Sitemap line in ${robotsPath}`);
}

// Keep index.html's social-card URLs absolute on the same origin.
const html = readFileSync(indexHtmlPath, 'utf8');
const nextHtml = html
  .replace(
    /(<meta property="og:image" content=")[^"]*(")/,
    `$1${siteUrl}/og.png$2`,
  )
  .replace(
    /(<meta name="twitter:image" content=")[^"]*(")/,
    `$1${siteUrl}/og.png$2`,
  );
if (nextHtml !== html) {
    writeFileSync(indexHtmlPath, nextHtml);
  console.log(`updated og/twitter image origins in ${indexHtmlPath}`);
}
